### ISSUE TITLE
Is this ready to share more widely?

### ISSUE THREAD

**Issue by peterc** [HarryR/vagrant-psql#2]
We're looking at linking to this project in http://postgresweekly.com/ this week but due to it going out today, we haven't got time to test. Just wanted to check in if the project is ready to share (or not) :-) Thanks!

**Comment by HarryR** [comment]
Hi Peter.

Honestly, I would hold-on until next week.

I created this project because the other vagrant boxes for PostgreSQL didn't handle the full lifecycle and would basically fall apart and/or destroy themselves and your data.

But it's not quite there yet, I need to make sure that people can entrust their data with this vagrant box and won't run into any surprises 6 months or a year down the line, and that it offers at least some easy & simple way of creating backups that can be archived & restored easily.

However, at the end of the day, it's your call.

**Comment by peterc** [comment]
No problem at all, that answer is totally why I wanted to check in :) Best of luck with the project!
